### ISSUE TITLE
你好，请问一下这个 MP3_BITRATE 是根据什么设置的呢？

### ISSUE THREAD

**Issue by davidditao** [litbubo/Streaming_media_based#1]
```
#define MP3_BITRATE     (128 * 1024) // correct bps:128*1024
```
如果这个值太小好像会产生卡顿。后面的注释中说这是 correct bps，想知道这个 correct 的值是如何得到的？

**Comment by litbubo** [comment]
![image](https://user-images.githubusercontent.com/87847512/166884951-f5d29377-29c4-476a-a7c9-2906cfcc2e25.png)
你好，这个值是歌曲的比特率，按照歌曲来设置的，因此媒体库中的歌曲需要有比特率限制

**Comment by davidditao** [comment]
嗷原来是这样，谢谢！！

**Comment by litbubo** [comment]
不客气，欢迎看看我升级后的Plus版本，这个是我做的一个备份

**Comment by davidditao** [comment]
哈哈哈我正打算研究一下呢
